### ISSUE TITLE
Move from optparse (deprecated) to argparse

### ISSUE THREAD

**Issue by jknotts** [jknotts/aqualid#2]
From Python docs (https://docs.python.org/2/library/optparse.html):

> Deprecated since version 2.7: The optparse module is deprecated and will not be developed further; development will continue with the argparse module.

**Comment by menify** [comment]
The main reason why optparse is used instead of [argsparse](https://docs.python.org/2/library/argparse.html) is that [argsparse](https://docs.python.org/2/library/argparse.html) is available only in Python 2.7 and Python 3.2 and above.
But there are systems with Python 2.6 and it would be good to be able to run Aqualid on such systems. Although such systems are getting away.

As I understand optparse is only deprecated. It's not going to be deleted near future.

Anyway I don't mind of such changes.

**Comment by jontayesp** [comment]
The argparse module looks compatible with 2.3+: https://pypi.python.org/pypi/argparse.

For older python versions where it is not installed be default, you can manually install: http://stackoverflow.com/questions/15330175/how-can-i-get-argparse-in-python-2-6.

I'm not sure if we need a library that is automatically available by default across all versions without any installation requirements. But you can always include argparse in the setup.py "install_requires" and distutils/setuptools will pull it in.

**Comment by jontayesp** [comment]
Also, thanks @menify for your help on these issues!

**Comment by menify** [comment]
Aquliad can be easily distributed as single standalone python script. It has no dependencies on external modules.
The main idea that developers of a source project may wish to keep Aquliad together their project's source code. And the source project can be distributed with Aquliad itself.

Users/developers should not care about dependencies. They just go to the project's root and run something like build.sh/bat, and it will call Aqualid.
Issue [#6](https://github.com/aqualid/aqualid/issues/6) is about embedding tools into standalone Aquliad.

Anyway I agree to drop support of Python 2.6 if there are any benefits or problems.

**Comment by jontayesp** [comment]
Ok, for 2.6 support without dependencies then yes optparse should be used.

**Comment by jontayesp** [comment]
Closing this for now. I think if we decide to drop 2.6 support (which is another conversation) then we can re-open this issue.
